src/Entity/TypeTournoi.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\TypeTournoiRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=TypeTournoiRepository::class)
 */
class TypeTournoi
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups("post:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="please enter nom")
     * @Groups("post:read")
     */
    private $nom_type;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="please enter description")
     * @Groups("post:read")
     */
    private $desc_type;

    /**
     * @ORM\OneToMany(targetEntity=Tournoi::class, mappedBy="tour")
     */
    private $tournois;

    public function __construct()
    {
        $this->tournois = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomType(): ?string
    {
        return $this->nom_type;
    }

    public function setNomType(string $nom_type): self
    {
        $this->nom_type = $nom_type;

        return $this;
    }

    public function getDescType(): ?string
    {
        return $this->desc_type;
    }

    public function setDescType(string $desc_type): self
    {
        $this->desc_type = $desc_type;

        return $this;
    }

    /**
     * @return Collection<int, Tournoi>
     */
    public function getTournois(): Collection
    {
        return $this->tournois;
    }

    public function addTournoi(Tournoi $tournoi): self
    {
        if (!$this->tournois->contains($tournoi)) {
            $this->tournois[] = $tournoi;
            $tournoi->setTour($this);
        }

        return $this;
    }

    public function removeTournoi(Tournoi $tournoi): self
    {
        if ($this->tournois->removeElement($tournoi)) {
            // set the owning side to null (unless already changed)
            if ($tournoi->getTour() === $this) {
                $tournoi->setTour(null);
            }
        }

        return $this;
    }

    public function __toString() {
        return (string) $this->id;
    }
}

src/Form/TypeTournoiType.php
<?php

namespace App\Form;

use App\Entity\TypeTournoi;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TypeTournoiType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_type')
            ->add('desc_type')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TypeTournoi::class,
        ]);
    }
}

src/Controller/TypeTournoiController.php
<?php

namespace App\Controller;

use App\Entity\TypeTournoi;
use App\Form\TypeTournoiType;
use App\Repository\TypeTournoiRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Validator\Constraints\Json;

/**
 * @Route("/type/tournoi")
 */
class TypeTournoiController extends AbstractController
{
    /**
     * @Route("/", name="type_tournoi_index", methods={"GET"})
     */
    public function index(TypeTournoiRepository $typeTournoiRepository): Response
    {
        return $this->render('type_tournoi/index.html.twig', [
            'type_tournois' => $typeTournoiRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="type_tournoi_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $typeTournoi = new TypeTournoi();
        $form = $this->createForm(TypeTournoiType::class, $typeTournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($typeTournoi);
            $entityManager->flush();

            return $this->redirectToRoute('type_tournoi_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('type_tournoi/new.html.twig', [
            'type_tournoi' => $typeTournoi,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}/edit", name="type_tournoi_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, TypeTournoi $typeTournoi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(TypeTournoiType::class, $typeTournoi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('type_tournoi_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('type_tournoi/edit.html.twig', [
            'type_tournoi' => $typeTournoi,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="type_tournoi_delete", methods={"POST"})
     */
    public function delete(Request $request, TypeTournoi $typeTournoi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeTournoi->getId(), $request->request->get('_token'))) {
            $entityManager->remove($typeTournoi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('type_tournoi_index', [], Response::HTTP_SEE_OTHER);
    }

/********************************mobile********************************************/



    /**
     * @Route("/addEmpJSON", name="typetour")
     */
    public function newTour(Request $request,NormalizerInterface  $normalizer)
    {
        $em= $this->getDoctrine()->getManager();
        $typetour= new TypeTournoi();
        $typetour->setNomType($request->get('NomType'));
        $typetour->setDescType($request->get('DescType'));
        $em->persist($typetour);
        $em->flush();
        $jsonContent =$normalizer->normalize($typetour,'json',['groups'=>'post:read']);
        return new Response(json_encode($jsonContent));
    }


    /**
     * @Route("/afficheTour", name="apiafficheTour")
     */
    public function AfficheApi(NormalizerInterface $Normalizer) {
        $agence=$this->getDoctrine()->getRepository(TypeTournoi::class)->findAll();

        $jsonContent=$Normalizer->normalize($agence,'json',['groups'=>'post:read']);


        return new Response(json_encode($jsonContent));

    }



    /**
     * @Route("/updatetour/{id}",name="updateEmp", methods={"GET","POST"})
     *
     */
    public function update(Request $request,$id,NormalizerInterface  $normalizer)
    {
        $em= $this->getDoctrine()->getManager();
        $type= $this->getDoctrine()->getRepository(TypeTournoi::class)->find($id);

        $type->setNomType($request->get('NomType'));
        $type->setDescType($request->get('DescType'));
        $em->persist($type);
        $em->flush();
        $jsonContent =$normalizer->normalize($type,'json',['groups'=>'post:read']);
        return new Response("Information updated successfully".json_encode($jsonContent));
    }



    /**
     * @Route("/supprimerTour/{id}",name="supprimertour")
     */
    public function supprimer(Request $request, NormalizerInterface  $normalizer, $id)

    {
        $em = $this -> getDoctrine() -> getManager();
        $tour = $em -> getRepository(TypeTournoi::class) -> find($id);
        $em -> remove($tour);
        $em -> flush();
        $jsonContent = $normalizer -> normalize($tour, 'json', ['groups' => 'post:read']);
        return new Response("Information deleted successfully" . json_encode($jsonContent));


    }



}

templates/type_tournoi/_delete_form.html.twig
<form method="post" action="{{ path('type_tournoi_delete', {'id': type_tournoi.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_tournoi.id) }}">
    <button  class="btn btn-danger btn-fw">Supprimer</button>
</form>

templates/type_tournoi/_form.html.twig
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Ajout Tournoi</h4>

            {{ form_start(form, {'attr': {'novalidate': 'novalidate'}}) }}
            <div class="form-group">
                {{ form_label(form.nom_type, 'Type De Tournoi'|trans, {'label_attr' : {'class': '' }}) }}
                {{ form_widget(form.nom_type, {'attr': {'class': 'form-control'}}) }}
            </div>

            <div class="form-group">
                {{ form_label(form.desc_type, 'Description type Tournoi'|trans, {'label_attr' : {'class': '' }}) }}
                {{ form_widget(form.desc_type, {'attr': {'class': 'form-control'}}) }}
            </div>

            <button  class="btn btn-outline-primary">{{ button_label|default('Save') }}</button>

            <a  class="btn btn-outline-primary" href="{{ path('tournoi_index') }}">back to list</a>
            {{ form_end(form) }}
        </div>
    </div>
</div>

templates/type_tournoi/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Edit TypeTournoi{% endblock %}

{% block body %}


    {{ include('type_tournoi/_form.html.twig', {'button_label': 'Update'}) }}



{% endblock %}

templates/type_tournoi/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}TypeTournoi index{% endblock %}

{% block body %}

    <div class="container-fluid page-body-wrapper">
        <div class="main-panel">
            <div class="content-wrapper">
                <div class="row">
                    <div class="col-lg-6 grid-margin stretch-card">
                    </div>
                    <div class="col-lg-12 grid-margin stretch-card">
                    </div>
                    <div class="col-lg-12 stretch-card">
                        <div class="card">
                            <div class="card-body">
                                <h2 class="card-title">Table Tournoi</h2>

                                <a href="{{ path('type_tournoi_new') }}" class="btn btn-success btn-fw">Ajouter</a>


                                <table class="table table-bordered">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Nom_type</th>
                                        <th>Desc_type</th>
                                        <th>actions</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for type_tournoi in type_tournois %}
                                        <tr class="table-primary">
                                            <td>{{ type_tournoi.id }}</td>
                                            <td>{{ type_tournoi.nomType }}</td>
                                            <td>{{ type_tournoi.descType }}</td>
                                            <td>
                                                <a class="btn btn-success btn-fw" href="{{ path('type_tournoi_edit', {'id': type_tournoi.id}) }}">Update</a>


                                            </td>
                                            <td>
                                                <div>{{ include('type_tournoi/_delete_form.html.twig') }}</div>
                                            </td>

                                        </tr>
                                    {% else %}
                                        <tr>
                                            <td colspan="4">no records found</td>
                                        </tr>
                                    {% endfor %}
                                    </tbody>
                                </table>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/type_tournoi/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New TypeTournoi{% endblock %}

{% block body %}


    {{ include('type_tournoi/_form.html.twig') }}

{% endblock %}